# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: mike bents
description: >- # this means to ignore newlines until "baseurl:"
 Experienced software engineer with advanced degree in software engineering. Server-side experience with web services, data integration, and streaming/processing data using Java, C#, and Node.js.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mbents.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_link: https://twitter.com/MikeBents
github_link:  https://github.com/mbents
about_summary: "I am a software engineer with over 13 years of experience and a M.S. in Software Engineering. My experience is mainly on the server side, creating, deploying, and maintaining web services; integrating data; and streaming and processing data. 
On the front end, I have worked on enterprise software for everything from customer data management to product design and development."
about_languages: Java, JavaScript, C#
about_cicd: Drone, Kubernetes, Docker
about_databases: MongoDB, SQL Server, MySQL, PostgreSQL, Kafka, Redis
about_frameworks: Spring, .NET, React, AngularJS


# Build settings
include: ['_pages']
kramdown:
  input: GFM
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
